# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronos', '0003_auto_20160310_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
